openapi: 3.0.0
info:
  title: Flask API with Swagger
  description: API documentation for authentication and file upload endpoints.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: Local server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login_or_register:
    post:
      summary: Login or Register a user
      description: Authenticates a user by mobile number and password. If the user does not exist, a new account is created.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobileNumber:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "400":
          description: Invalid credentials

  /upload:
    post:
      summary: Upload an image
      description: Uploads an image file to the server.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: File uploaded successfully
        "400":
          description: No file selected or invalid file format

  /searchHistory:
    get:
      summary: Get upload history
      description: Retrieves the list of uploaded images with their disease predictions.
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of upload history

  /display/{filename}:
    get:
      summary: Display an uploaded image
      description: Fetches an image by filename.
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Image returned
        "404":
          description: File not found