"""Updated disease_name to 100

Revision ID: 8e0d95fbd8b1
Revises: 5a87d8e402ba
Create Date: 2025-03-01 03:48:59.550430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0d95fbd8b1'
down_revision = '5a87d8e402ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_histories', schema=None) as batch_op:
        batch_op.alter_column('disease_name',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_histories', schema=None) as batch_op:
        batch_op.alter_column('disease_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
